### ISSUE TITLE
Permission issue when using IAM Instance Profiles.

### ISSUE THREAD

**Issue by joharohl** [WhoopInc/mkwheelhouse#13]
Firstly, thanks for the awesome package! It's currently saving us a lot of grief.

Secondly, the fix for #11 has broken mkwheelhouse for me. We are using IAM Instance Profiles on CI machines that run mkwheelhouse. I'm getting 403 Unauthorized errors when it [tries to load the bucket](https://github.com/WhoopInc/mkwheelhouse/blob/master/mkwheelhouse.py#L48-L49). It seems that unsetting the `self.s3.provider.security_token` messes with the authentication. 

I am not 100% sure if the cause is new since I haven't used mkwheelhouse in a while.

I have made a fix over at https://github.com/joharohl/mkwheelhouse/commit/8b500be0117d5eb0a3d3544c820bb968f07eec31 if anyone has similar issues.

I can make a PR, but I would need to possibly tidy things up, and I don't know if this is the way you would like to solve it.

**Comment by benesch** [comment]
So glad you find mkwheelhouse useful! Sorry to have broken your workflow!

Your fix is clever. Are you set to maintain your fork for a few weeks? If you don't mind, I think I'd like to try to get this fixed upstream. At least a few other packages seem to have incorporated the flawed `security_token =''` fix. Seems like it's time to get this fixed properly. Failing that, I'll integrate your patch!

**Comment by joharohl** [comment]
No worries.

I had a look at boto/boto#1477 and its almost 4 year clock time and thought it would never be fixed. Putting in the effort and fixing it there is of course a much better idea :).

**Comment by Evnsan** [comment]
Hello everyone,
We are also suffering from this issue.
Do you have any prediction of when this problem will be solved?
The joharohl's solution works great for us, but it would be great to stay on the main line.

Many thanks for the package and I'm sorry for the bad english

**Comment by benesch** [comment]
I've wholesale merged @joharohl's patch, so this should be fixed on the latest master! Want to give it a try @Evnsan?
